import type { Metadata } from "next";
import "./globals.css";
import { leagueSpartan } from "./ui/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.className} antialiased text-base`}>
        {children}
      </body>
    </html>
  );
}
